inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-rspec

RSpec/MethodCallWithArgsParentheses:
  Exclude:
    - "spec/**/*.rb"
RSpec/ContextWording:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
